import { MerchItem } from '@/types'

export const MERCH_ITEMS: Record<string, MerchItem> = {
  look_01: {
    id: 'look_01',
    name: 'Balaa Black Hoodie',
    description: 'Heavyweight brushed fleece hoodie with embroidered signature BALAA branding.',
    price: 1780,
    originalPrice: 8900,
    image: '/library/clothes/balaa_black_hoodie.webp',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stripePriceId: 'price_balaa_black_hoodie',
    meshName: 'outfit_top',
  },
  look_02: {
    id: 'look_02',
    name: 'Balaa Black T-EE',
    description: '100% heavyweight cotton studio tee with contrast jet black BALAA branding.',
    price: 900,
    originalPrice: 4500,
    image: '/library/clothes/balaa_black_t_ee.webp',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stripePriceId: 'price_balaa_black_tee',
    meshName: 'outfit_top',
  },
  look_03: {
    id: 'look_03',
    name: 'Balaa Black and White Sweatshirt',
    description: 'Dual-tone contrast athletic sweatshirt with high-density BALAA crest.',
    price: 1500,
    originalPrice: 7500,
    image: '/library/clothes/balaa_black_and_white_sweatshirt.webp',
    sizes: ['S', 'M', 'L', 'XL'],
    stripePriceId: 'price_balaa_bw_sweatshirt',
    meshName: 'outfit_top',
  },
  look_04: {
    id: 'look_04',
    name: 'Balaa Black and White Hoodie',
    description: 'Signature tailored two-tone fleece hoodie with embroidered BALAA typography.',
    price: 1780,
    originalPrice: 8900,
    image: '/library/clothes/balaa_black_and_white_hoodie.webp',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stripePriceId: 'price_balaa_bw_hoodie',
    meshName: 'outfit_top',
  },
  look_05: {
    id: 'look_05',
    name: 'Balaa Sweatshirt',
    description: 'Ultra-plush French terry knit pullover in deep studio charcoal.',
    price: 1500,
    originalPrice: 7500,
    image: '/library/clothes/balaa_sweatshirt.webp',
    sizes: ['S', 'M', 'L', 'XL'],
    stripePriceId: 'price_balaa_sweatshirt',
    meshName: 'outfit_top',
  },
  look_06: {
    id: 'look_06',
    name: 'Balaa White Left Chest Logo Hoodie',
    description: 'Optical white concert hoodie with minimalist left-chest BALAA logo embroidery.',
    price: 1780,
    originalPrice: 8900,
    image: '/library/clothes/balaa_white_left_chest_logo_hoodie.webp',
    sizes: ['S', 'M', 'L', 'XL'],
    stripePriceId: 'price_balaa_white_left_logo_hoodie',
    meshName: 'outfit_top',
  },
  look_07: {
    id: 'look_07',
    name: 'Balaa White Sweater',
    description: 'Warm white heavyweight fleece sweater with tonal BALAA studio emblem.',
    price: 1500,
    originalPrice: 7500,
    image: '/library/clothes/balaa_white_sweater.webp',
    sizes: ['S', 'M', 'L', 'XL'],
    stripePriceId: 'price_balaa_white_sweater',
    meshName: 'outfit_top',
  },
  look_08: {
    id: 'look_08',
    name: 'Balaa White T-EE',
    description: 'Crisp optical white studio tee with contrast jet black BALAA branding.',
    price: 900,
    originalPrice: 4500,
    image: '/library/clothes/balaa_white_t_ee.webp',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stripePriceId: 'price_balaa_white_tee',
    meshName: 'outfit_top',
  },
  look_09: {
    id: 'look_09',
    name: 'Balaa White Hoodie',
    description: 'High-visibility white concert hoodie with black contrast drawstring accents.',
    price: 1780,
    originalPrice: 8900,
    image: '/library/clothes/balaa_white_hoodie.webp',
    sizes: ['S', 'M', 'L', 'XL'],
    stripePriceId: 'price_balaa_white_hoodie',
    meshName: 'outfit_top',
  },
  look_10: {
    id: 'look_10',
    name: 'Balaa Black Left Chest Logo Hoodie',
    description: 'Underground edition: Deep black hoodie with embroidered left chest BALAA crest.',
    price: 1780,
    originalPrice: 8900,
    image: '/library/clothes/balaa_black_left_chest_logo_hoodie.webp',
    sizes: ['S', 'M', 'L', 'XL'],
    stripePriceId: 'price_balaa_black_left_logo_hoodie',
    meshName: 'outfit_top',
  },
}

export const MERCH_BY_MESH = new Map<string, MerchItem>(
  Object.values(MERCH_ITEMS)
    .filter((m) => m.meshName)
    .map((m) => [m.meshName, m])
)

export const findMerchByMesh = (meshName: string): MerchItem | undefined =>
  MERCH_BY_MESH.get(meshName)
